import { useState } from 'react';
import {
  ArrowRight, BadgeCheck, Check, ChevronDown, Clock3, Copy, FileCheck2,
  LockKeyhole, Mail, ShieldCheck, Sparkle, TimerReset, WalletCards,
} from 'lucide-react';
import '../swap-convert-redesign/_group.css';

type Stage = 'request' | 'confirmed';

export function HumanSettlementReview() {
  const [stage, setStage] = useState<Stage>('request');
  const [copied, setCopied] = useState(false);
  const confirmed = stage === 'confirmed';
  const copyReference = () => {
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1600);
  };

  return <main className="hsr-shell">
    <style>{`
      .hsr-shell{min-height:100%;box-sizing:border-box;padding:20px;background:hsl(var(--background));color:hsl(var(--foreground));font-family:'Plus Jakarta Sans',sans-serif}
      .hsr-shell *{box-sizing:border-box}.hsr-shell button{cursor:pointer}.hsr-wrap{max-width:1180px;margin:0 auto}
      .hsr-top{height:46px;display:flex;align-items:center;justify-content:space-between;margin-bottom:14px}.hsr-brand{display:flex;align-items:center;gap:8px;font:600 15px 'Space Grotesk',sans-serif;letter-spacing:-.06em}.hsr-mark{display:grid;place-items:center;width:27px;height:27px;color:hsl(var(--primary));border:2px solid currentColor;border-radius:9px 9px 4px 9px;transform:rotate(-11deg)}.hsr-mark svg{transform:rotate(11deg)}.hsr-brand b{color:hsl(var(--primary))}.hsr-topmeta{font:500 10px 'JetBrains Mono',monospace;color:hsl(var(--muted-foreground));display:flex;align-items:center;gap:9px}.hsr-topmeta i{width:6px;height:6px;border-radius:50%;background:hsl(var(--success));box-shadow:0 0 0 4px hsl(var(--success)/.12)}
      .hsr-grid{display:grid;grid-template-columns:minmax(0,1.58fr) minmax(290px,.72fr);gap:16px}.hsr-main,.hsr-side{background:hsl(var(--card));border:1px solid hsl(var(--card-border));box-shadow:0 10px 32px hsl(224 40% 12%/.045)}.hsr-main{border-radius:20px;overflow:hidden}.hsr-side{border-radius:20px;padding:19px}
      .hsr-hero{padding:23px 25px 20px;background:hsl(var(--primary));color:hsl(var(--primary-foreground));position:relative;overflow:hidden}.hsr-hero:after{content:"";position:absolute;width:175px;height:175px;border:1px solid hsl(var(--primary-foreground)/.22);border-radius:50%;right:-35px;top:-73px;box-shadow:0 0 0 28px hsl(var(--primary-foreground)/.06),0 0 0 58px hsl(var(--primary-foreground)/.04)}.hsr-eyebrow{font:500 10px 'JetBrains Mono',monospace;letter-spacing:1.2px;color:hsl(var(--primary-foreground)/.74);display:flex;align-items:center;gap:7px}.hsr-eyebrow span{width:15px;height:1px;background:currentColor}.hsr-titleline{display:flex;justify-content:space-between;gap:18px;align-items:end;margin-top:8px;position:relative;z-index:1}.hsr-title{font:600 30px/1.03 'Space Grotesk',sans-serif;letter-spacing:-.06em;margin:0;max-width:435px}.hsr-id{font:500 10px 'JetBrains Mono',monospace;color:hsl(var(--primary-foreground)/.76);border:1px solid hsl(var(--primary-foreground)/.22);padding:7px 9px;border-radius:7px;white-space:nowrap}.hsr-progress{display:flex;align-items:center;gap:6px;margin-top:21px;position:relative;z-index:1}.hsr-progress span{height:3px;flex:1;background:hsl(var(--primary-foreground)/.26);border-radius:4px}.hsr-progress span.active{background:hsl(var(--accent))}.hsr-progress b{font:500 9px 'JetBrains Mono',monospace;color:hsl(var(--primary-foreground)/.76);margin-left:5px}
      .hsr-settlement{padding:20px 25px 14px}.hsr-sectionlabel{font:700 10px 'JetBrains Mono',monospace;color:hsl(var(--primary));letter-spacing:1.05px}.hsr-route{display:grid;grid-template-columns:1fr 38px 1fr;align-items:center;margin:13px 0 17px}.hsr-asset{padding:13px 0;border-bottom:1px solid hsl(var(--border))}.hsr-asset small{display:block;font-size:10px;color:hsl(var(--muted-foreground));margin-bottom:5px}.hsr-asset strong{font:600 20px/1 'JetBrains Mono',monospace;letter-spacing:-.06em}.hsr-asset div{font:500 10px 'JetBrains Mono',monospace;margin-top:7px;color:hsl(var(--muted-foreground))}.hsr-asset.to{text-align:right}.hsr-routeicon{margin:auto;color:hsl(var(--primary));display:grid;place-items:center}.hsr-summary{display:grid;grid-template-columns:repeat(3,1fr);border:1px solid hsl(var(--border));border-radius:12px;overflow:hidden}.hsr-summary div{padding:10px 11px;border-right:1px solid hsl(var(--border))}.hsr-summary div:last-child{border:0}.hsr-summary span{display:block;color:hsl(var(--muted-foreground));font-size:9px;margin-bottom:4px}.hsr-summary b{font-size:11px}.hsr-summary .warm{color:hsl(var(--info))}
      .hsr-review{margin:6px 25px 23px;padding:15px 16px;border:1px solid hsl(var(--info)/.3);border-radius:14px;background:hsl(var(--info)/.08);display:flex;gap:12px;align-items:flex-start}.hsr-review>svg{color:hsl(var(--info));margin-top:2px;flex:none}.hsr-review h2{margin:0 0 4px;font-size:12px}.hsr-review p{margin:0;color:hsl(var(--muted-foreground));font-size:10px;line-height:1.55;max-width:530px}.hsr-review b{color:hsl(var(--foreground))}.hsr-review .hsr-confirmed{color:hsl(var(--success))}
      .hsr-details{border-top:1px solid hsl(var(--border));padding:18px 25px 20px}.hsr-detailshead{display:flex;justify-content:space-between;align-items:center;margin-bottom:12px}.hsr-detailshead h2{font:600 15px 'Space Grotesk',sans-serif;margin:0;letter-spacing:-.05em}.hsr-detailshead button{color:hsl(var(--primary));border:0;background:transparent;font:700 10px 'Plus Jakarta Sans',sans-serif}.hsr-address{display:flex;align-items:center;gap:10px;padding:10px 11px;border-radius:10px;background:hsl(var(--muted)/.58);border:1px solid hsl(var(--border))}.hsr-address .addressicon{width:25px;height:25px;border-radius:7px;background:hsl(var(--primary)/.1);color:hsl(var(--primary));display:grid;place-items:center;flex:none}.hsr-address span{min-width:0;flex:1}.hsr-address small{display:block;color:hsl(var(--muted-foreground));font-size:9px}.hsr-address code{display:block;margin-top:2px;font:400 10px 'JetBrains Mono',monospace;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.hsr-copy{border:0;background:transparent;color:hsl(var(--primary));padding:4px;display:grid;place-items:center}
      .hsr-sidehead{display:flex;align-items:center;justify-content:space-between}.hsr-sidehead .badge{width:31px;height:31px;border-radius:10px;background:hsl(var(--info)/.1);color:hsl(var(--info));display:grid;place-items:center}.hsr-sidehead span{font:500 9px 'JetBrains Mono',monospace;color:hsl(var(--muted-foreground))}.hsr-side h2{font:600 24px/1.05 'Space Grotesk',sans-serif;letter-spacing:-.06em;margin:14px 0 6px}.hsr-side>p{font-size:10px;line-height:1.55;color:hsl(var(--muted-foreground));margin:0 0 18px}.hsr-specialist{padding:13px;border-radius:13px;background:hsl(var(--info)/.08);border:1px solid hsl(var(--info)/.2)}.hsr-person{display:flex;gap:9px;align-items:center}.hsr-avatar{display:grid;place-items:center;width:31px;height:31px;border-radius:50%;background:hsl(var(--primary)/.12);color:hsl(var(--primary));font:700 10px 'Space Grotesk',sans-serif}.hsr-person strong{display:block;font-size:11px}.hsr-person span{display:block;font-size:9px;color:hsl(var(--muted-foreground));margin-top:2px}.hsr-ready{margin-top:11px;font:500 9px 'JetBrains Mono',monospace;color:hsl(var(--info));display:flex;align-items:center;gap:5px}.hsr-ready i{width:6px;height:6px;border-radius:50%;background:hsl(var(--info))}
      .hsr-timing{margin-top:17px;border-top:1px solid hsl(var(--border));padding-top:15px}.hsr-timing h3{font:700 10px 'JetBrains Mono',monospace;letter-spacing:1px;color:hsl(var(--primary));margin:0 0 12px}.hsr-step{display:grid;grid-template-columns:24px 1fr;gap:9px;position:relative;padding-bottom:14px}.hsr-step:last-child{padding-bottom:0}.hsr-step:not(:last-child):after{content:"";position:absolute;height:13px;border-left:1px dashed hsl(var(--border));left:11px;top:22px}.hsr-stepicon{width:23px;height:23px;border-radius:50%;background:hsl(var(--muted));color:hsl(var(--muted-foreground));display:grid;place-items:center}.hsr-step.done .hsr-stepicon{background:hsl(var(--success)/.12);color:hsl(var(--success))}.hsr-step.current .hsr-stepicon{background:hsl(var(--info)/.12);color:hsl(var(--info))}.hsr-step b{display:block;font-size:10px}.hsr-step span{display:block;margin-top:2px;font-size:9px;color:hsl(var(--muted-foreground));line-height:1.35}.hsr-action{width:100%;display:flex;align-items:center;justify-content:center;gap:8px;border:0;border-radius:10px;background:hsl(var(--primary));color:hsl(var(--primary-foreground));padding:12px 13px;margin-top:18px;font:700 11px 'Plus Jakarta Sans',sans-serif}.hsr-action.confirmed{background:hsl(var(--success))}.hsr-footnote{display:flex;gap:6px;margin:11px 2px 0;color:hsl(var(--muted-foreground));font-size:8.5px;line-height:1.4}.hsr-footnote svg{flex:none;margin-top:1px}
      @media(max-width:800px){.hsr-grid{grid-template-columns:1fr}.hsr-side{display:grid;grid-template-columns:1fr 1fr;gap:16px}.hsr-side>p{margin-bottom:0}.hsr-timing,.hsr-action,.hsr-footnote{grid-column:1/-1}.hsr-timing{display:flex;gap:10px}.hsr-step{flex:1;padding-bottom:0}.hsr-step:not(:last-child):after{height:0;width:10px;border-left:0;border-top:1px dashed hsl(var(--border));left:auto;right:-5px;top:11px}}
      @media(max-width:520px){.hsr-shell{padding:13px}.hsr-topmeta{display:none}.hsr-hero,.hsr-settlement,.hsr-details{padding-left:17px;padding-right:17px}.hsr-review{margin-left:17px;margin-right:17px}.hsr-title{font-size:25px}.hsr-titleline{align-items:flex-start;flex-direction:column}.hsr-route{grid-template-columns:1fr 28px 1fr}.hsr-asset strong{font-size:16px}.hsr-summary{grid-template-columns:1fr}.hsr-summary div{border-right:0;border-bottom:1px solid hsl(var(--border))}.hsr-summary div:last-child{border-bottom:0}.hsr-side{display:block}.hsr-side>p{margin-bottom:16px}.hsr-timing{display:block}.hsr-step{padding-bottom:14px}.hsr-step:not(:last-child):after{height:13px;width:0;border-top:0;border-left:1px dashed hsl(var(--border));left:11px;right:auto;top:22px}}
    `}</style>
    <div className="hsr-wrap">
      <header className="hsr-top"><div className="hsr-brand"><span className="hsr-mark"><Sparkle size={14} /></span>Quick<span style={{ color: 'hsl(var(--primary))' }}>X</span><b>change</b></div><div className="hsr-topmeta"><i /> HUMAN-SUPERVISED DESK</div></header>
      <div className="hsr-grid">
        <section className="hsr-main">
          <div className="hsr-hero"><div className="hsr-eyebrow"><span /> HUMAN SETTLEMENT DESK</div><div className="hsr-titleline"><h1 className="hsr-title">{confirmed ? 'Your route is ready for settlement.' : 'A specialist will confirm your route.'}</h1><code className="hsr-id">QX–8472–MJ</code></div><div className="hsr-progress"><span className="active" /><span className={confirmed ? 'active' : ''} /><span /><b>{confirmed ? '02 / 03' : '01 / 03'}</b></div></div>
          <div className="hsr-settlement"><div className="hsr-sectionlabel">YOUR SETTLEMENT</div><div className="hsr-route"><div className="hsr-asset"><small>YOU SEND</small><strong>2,500.00 USD</strong><div>Wise transfer</div></div><div className="hsr-routeicon"><ArrowRight size={20} /></div><div className="hsr-asset to"><small>YOU RECEIVE</small><strong>2,471.25 USDC</strong><div>Polygon network</div></div></div><div className="hsr-summary"><div><span>Indicative rate</span><b>1 USD = 0.9885 USDC</b></div><div><span>Network fee</span><b>Included</b></div><div><span>Route validity</span><b className="warm">15 minutes</b></div></div></div>
          <div className="hsr-review">{confirmed ? <BadgeCheck size={18} /> : <FileCheck2 size={18} />}<div><h2 className={confirmed ? 'hsr-confirmed' : ''}>{confirmed ? 'Specialist confirmation recorded' : 'Why this route gets a human review'}</h2><p>{confirmed ? <>Your payment invitation is ready. Send exactly <b>2,500.00 USD</b> from the account you nominated.</> : <>A settlement specialist verifies the recipient, network and return path <b>before payment is invited.</b> Review begins after submission.</>}</p></div></div>
          <div className="hsr-details"><div className="hsr-detailshead"><h2>Settlement destination</h2><button onClick={() => setStage('request')}>Edit route</button></div><div className="hsr-address"><div className="addressicon"><WalletCards size={14} /></div><span><small>POLYGON · USDC</small><code>0x9df7A1bcE382d79F4d9bE2c47baef3d5</code></span><button className="hsr-copy" onClick={copyReference} aria-label="Copy destination address">{copied ? <Check size={15} /> : <Copy size={15} />}</button></div></div>
        </section>
        <aside className="hsr-side"><div><div className="hsr-sidehead"><span>DESK REVIEW</span><div className="badge"><TimerReset size={16} /></div></div><h2>{confirmed ? 'Confirmation is recorded.' : 'Human-supervised settlement.'}</h2><p>{confirmed ? 'The specialist confirmation stage is complete. Payment is still awaiting your invitation.' : 'A settlement specialist checks your route after you submit. You will receive an email at each stage.'}</p><div className="hsr-specialist"><div className="hsr-person"><div className="hsr-avatar"><ShieldCheck size={15} /></div><div><strong>Settlement specialist</strong><span>Human-supervised desk</span></div></div><div className="hsr-ready"><i /> REVIEW BEGINS AFTER SUBMISSION</div></div></div>
          <div className="hsr-timing"><h3>REVIEW TIMING · ESTIMATE</h3><div className="hsr-step done"><div className="hsr-stepicon"><Check size={12} /></div><div><b>Route received</b><span>Request draft · QX–8472–MJ</span></div></div><div className={`hsr-step ${confirmed ? 'done' : 'current'}`}><div className="hsr-stepicon">{confirmed ? <Check size={12} /> : <Clock3 size={12} />}</div><div><b>Specialist confirmation</b><span>{confirmed ? 'Recorded after request' : 'Estimated review: ~15 min'}</span></div></div><div className="hsr-step"><div className="hsr-stepicon"><ChevronDown size={12} /></div><div><b>Payment invitation</b><span>After confirmation · by email</span></div></div></div>
          <button className={`hsr-action ${confirmed ? 'confirmed' : ''}`} onClick={() => setStage(confirmed ? 'request' : 'confirmed')}>{confirmed ? <><Mail size={14} /> Return to route review <ArrowRight size={14} /></> : <><ShieldCheck size={14} /> Request specialist confirmation <ArrowRight size={14} /></>}</button><div className="hsr-footnote"><LockKeyhole size={11} /> We only use your email to coordinate this settlement and any return of funds.</div>
        </aside>
      </div>
    </div>
  </main>;
}