import { useEffect, useRef, useState } from 'react';
import { ArrowDownUp, ArrowRight, Check, ChevronDown, CircleAlert, Clock3, Copy, Mail, Menu, Search, ShieldCheck, UserRound, Wallet, Zap } from 'lucide-react';
import brandLogo from '../../../../../crypto-exchange-widget/public/brand/quickxchange-header-light.png';
import './Refined.css';

type Mode = 'swap' | 'convert';
type Asset = { id: string; symbol: string; name: string; network: string; color: string; payment?: boolean };
const swapAssets: Asset[] = [
  { id: 'usd-wise', symbol: 'USD', name: 'Wise', network: 'Wise', color: '#a9dc70', payment: true }, { id: 'usd-bank', symbol: 'USD', name: 'Bank transfer', network: 'ACH', color: '#315de5', payment: true },
  { id: 'usdt-trc20', symbol: 'USDT', name: 'Tether', network: 'TRON (TRC20)', color: '#26a17b' }, { id: 'usdc-eth', symbol: 'USDC', name: 'USD Coin', network: 'Ethereum (ERC20)', color: '#2775ca' }, { id: 'btc', symbol: 'BTC', name: 'Bitcoin', network: 'Bitcoin', color: '#e99b36' },
];
const convertAssets: Asset[] = [{ id: 'btc', symbol: 'BTC', name: 'Bitcoin', network: 'Bitcoin', color: '#e99b36' }, { id: 'eth', symbol: 'ETH', name: 'Ethereum', network: 'Ethereum', color: '#6477d7' }, ...swapAssets.slice(2), { id: 'sol', symbol: 'SOL', name: 'Solana', network: 'Solana', color: '#7b61ff' }];
const rates: Record<string, number> = { 'usd-wise:usdt-trc20': .9824, 'usd-wise:usdc-eth': .9811, 'usd-wise:btc': .00001482, 'usd-bank:usdt-trc20': .9768, 'usdt-trc20:usdc-eth': .9982, 'usdt-trc20:btc': .00001508, 'btc:eth': 21.6743, 'btc:usdt-trc20': 66312.42, 'eth:btc': .04612, 'eth:usdt-trc20': 3059.74, 'usdc-eth:btc': .00001504, 'sol:usdt-trc20': 142.71 };
const fmt = (value: number) => new Intl.NumberFormat('en-US', { maximumFractionDigits: 6 }).format(value);

function Identity({ asset, small = false }: { asset: Asset; small?: boolean }) {
  return <span className="rx-identity"><span className="rx-coin" style={{ background: asset.color }}>{asset.payment ? asset.name[0] : asset.symbol[0]}</span><span><b>{asset.symbol}</b>{!small && <small>{asset.name}</small>}<i>{asset.network}</i></span></span>;
}
function Picker({ value, options, onChange, label }: { value: string; options: Asset[]; onChange: (id: string) => void; label: string }) {
  const [open, setOpen] = useState(false); const [query, setQuery] = useState(''); const root = useRef<HTMLDivElement>(null);
  const selected = options.find(x => x.id === value) ?? options[0]; const filtered = options.filter(x => `${x.symbol} ${x.name} ${x.network}`.toLowerCase().includes(query.toLowerCase()));
  useEffect(() => { const close = (e: PointerEvent) => !root.current?.contains(e.target as Node) && setOpen(false); if (open) document.addEventListener('pointerdown', close); return () => document.removeEventListener('pointerdown', close); }, [open]);
  const id = label.replace(/ /g, '-').toLowerCase();
  return <div className="rx-picker" ref={root}><button data-testid={`button-${id}`} type="button" aria-label={label} aria-expanded={open} onClick={() => setOpen(!open)}><Identity asset={selected} small /><ChevronDown size={15} /></button>{open && <div className="rx-menu"><label><Search size={14}/><input data-testid={`input-search-${id}`} autoFocus value={query} onChange={e => setQuery(e.target.value)} placeholder="Search currency" /></label>{filtered.map(x => <button data-testid={`button-asset-${x.id}`} type="button" key={x.id} onClick={() => { onChange(x.id); setOpen(false); setQuery(''); }}><Identity asset={x}/>{x.id === selected.id && <Check size={15}/>}</button>)}{!filtered.length && <p>No currencies match.</p>}</div>}</div>;
}
export function Refined() {
  const [mode, setMode] = useState<Mode>('swap'); const [amount, setAmount] = useState(''); const [fromId, setFromId] = useState('usd-wise'); const [toId, setToId] = useState('usdt-trc20'); const [rateMode, setRateMode] = useState<'FLOATING'|'FIXED'>('FLOATING');
  const [email, setEmail] = useState(''); const [destination, setDestination] = useState(''); const [destinationMemo, setDestinationMemo] = useState(''); const [refund, setRefund] = useState(''); const [refundMemo, setRefundMemo] = useState(''); const [name, setName] = useState(''); const [note, setNote] = useState(''); const [status, setStatus] = useState<'success'|'error'|''>('');
  const assets = mode === 'swap' ? swapAssets : convertAssets; const from = assets.find(x => x.id === fromId) ?? assets[0]; const targets = assets.filter(x => x.id !== from.id); const to = targets.find(x => x.id === toId) ?? targets[0]; const n = Number(amount); const rate = rates[`${from.id}:${to.id}`] ?? (to.symbol === 'BTC' ? .00001504 : from.symbol === 'BTC' ? 66312.42 : .9874); const receive = n > 0 && Number.isFinite(n) ? n * rate : 0; const fee = receive * (mode === 'swap' ? .012 : .006); const ready = receive > 0;
  const selectMode = (next: Mode) => { setMode(next); setAmount(''); setStatus(''); setFromId(next === 'swap' ? 'usd-wise' : 'btc'); setToId(next === 'swap' ? 'usdt-trc20' : 'eth'); };
  const submit = (e: React.FormEvent) => { e.preventDefault(); if (!ready) return setStatus('error'); setStatus('success'); };
  return <div className="rx-shell"><header className="rx-header"><button data-testid="button-home" type="button" className="rx-logo"><img src={brandLogo} alt="QuickXchange" /></button><nav><button data-testid="button-exchange" className="active">Exchange</button><button data-testid="button-track-order">Track order</button><button data-testid="button-account">Account</button></nav><span className="rx-online"><i/> Desk online</span><button data-testid="button-menu" type="button" className="rx-menu-button" aria-label="Open navigation"><Menu size={19}/></button></header>
    <main><section className="rx-intro"><p className="rx-eyebrow">QUICKXCHANGE · EXCHANGE DESK</p><h1>Know the route.<br/><em>Then make the move.</em></h1><p className="rx-lede">A carefully supervised exchange handoff, with every currency, network, and expected amount made clear before you commit.</p><div className="rx-assurances"><span><ShieldCheck size={16}/> No custody held</span><span><Clock3 size={16}/> Clear confirmations</span></div></section>
      <form className="rx-card" onSubmit={submit}><div className="rx-card-head"><div><p className="rx-eyebrow">ORDER BUILDER</p><h2>Set your exchange</h2></div><span><ShieldCheck size={14}/> Protected handoff</span></div><div className="rx-tabs"><button data-testid="button-mode-swap" type="button" className={mode === 'swap' ? 'active' : ''} onClick={() => selectMode('swap')}>Swap <small>desk reviewed</small></button><button data-testid="button-mode-convert" type="button" className={mode === 'convert' ? 'active' : ''} onClick={() => selectMode('convert')}>Convert <small>automatic</small></button></div>
        <div className="rx-field"><label>You send</label><div><input data-testid="input-send-amount" value={amount} onChange={e => { setAmount(e.target.value); setStatus(''); }} inputMode="decimal" placeholder="0.00"/><Picker value={from.id} options={assets} onChange={id => { setFromId(id); setStatus(''); }} label="Send currency"/></div></div>
        <button data-testid="button-switch-assets" type="button" className="rx-switch" aria-label="Switch currencies" onClick={() => { const next = assets.find(x => x.id === to.id); if (next) { setFromId(to.id); setToId(from.id); }}}><ArrowDownUp size={16}/></button>
        <div className="rx-field rx-receive"><label>You receive <small>{mode === 'swap' ? 'estimated after desk fee' : 'at current quote'}</small></label><div><input data-testid="text-receive-amount" readOnly value={ready ? fmt(mode === 'swap' ? receive-fee : receive) : ''} placeholder={amount ? 'Checking route…' : '0.00'}/><Picker value={to.id} options={targets} onChange={id => { setToId(id); setStatus(''); }} label="Receive currency"/></div></div>
        {mode === 'swap' ? <section className={`rx-route ${ready ? '' : 'pending'}`}><div><p>ROUTE REVIEW</p><b>{from.network} <ArrowRight size={13}/> {to.network}</b></div><span>{ready ? 'Available' : 'Awaiting amount'}</span><dl><div><dt>Rate</dt><dd>{ready ? fmt(rate) : '—'}</dd></div><div><dt>Desk fee</dt><dd>{ready ? `${fmt(fee)} ${to.symbol}` : '—'}</dd></div><div><dt>Expected time</dt><dd>{ready ? '~15 min' : '—'}</dd></div></dl>{!ready && <small>Enter an amount to check availability for this route.</small>}</section> : <><fieldset className="rx-rate"><legend>RATE MODE</legend>{(['FLOATING','FIXED'] as const).map(x => <button data-testid={`button-rate-${x.toLowerCase()}`} type="button" onClick={() => setRateMode(x)} className={rateMode === x ? 'active' : ''} key={x}><b>{x === 'FLOATING' ? 'Floating rate' : 'Fixed rate'}</b><small>{x === 'FLOATING' ? 'Live provider rate' : 'Protected for this quote'}</small></button>)}</fieldset>{ready && <section className="rx-quote"><b>Quote details</b><span><Clock3 size={13}/> Refreshes in 42s</span><dl><div><dt>Exchange rate</dt><dd>1 {from.symbol} = {fmt(rate)} {to.symbol}</dd></div><div><dt>Network fee</dt><dd>Included</dd></div><div><dt>Expected time</dt><dd>~5–15 mins</dd></div></dl></section>}</>}
        <div className="rx-details"><p>WHERE SHOULD WE SEND IT?</p><label><span>Email address</span><span className="rx-input"><Mail size={15}/><input data-testid="input-email" required type="email" value={email} onChange={e => setEmail(e.target.value)} placeholder="you@example.com"/></span></label>{mode === 'swap' && <label><span>Your name <small>optional</small></span><span className="rx-input"><UserRound size={15}/><input data-testid="input-name" value={name} onChange={e => setName(e.target.value)} placeholder="Name on the order"/></span></label>}<label><span>Destination address <small>{to.symbol} · {to.network}</small></span><span className="rx-input"><Wallet size={15}/><input data-testid="input-destination" required value={destination} onChange={e => setDestination(e.target.value)} placeholder={`Your ${to.symbol} receiving address`}/></span></label><label><span>Destination memo <small>optional</small></span><input data-testid="input-destination-memo" value={destinationMemo} onChange={e => setDestinationMemo(e.target.value)} placeholder="Tag or memo if required"/></label>{mode === 'convert' && <><label><span>Refund address <small>{from.symbol}</small></span><input data-testid="input-refund" required value={refund} onChange={e => setRefund(e.target.value)} placeholder={`Your ${from.symbol} refund address`}/></label><label><span>Refund memo <small>optional</small></span><input data-testid="input-refund-memo" value={refundMemo} onChange={e => setRefundMemo(e.target.value)} placeholder="Tag or memo if required"/></label></>}{mode === 'swap' && <label><span>Order note <small>optional</small></span><textarea data-testid="input-note" value={note} onChange={e => setNote(e.target.value)} placeholder="Anything the desk should know?"/></label>}</div>
        <button data-testid="button-submit-order" className="rx-submit" disabled={!ready}><span>{mode === 'swap' ? <ShieldCheck size={17}/> : <Zap size={17}/>} {mode === 'swap' ? 'Submit swap request' : 'Start conversion'}</span><ArrowRight size={17}/></button>{status === 'success' && <div data-testid="status-success" className="rx-status success"><Check size={16}/>{mode === 'swap' ? 'Your request is ready. A desk operator will confirm the final amount.' : 'Your conversion order is ready and the destination addresses were validated.'}</div>}{status === 'error' && <div data-testid="status-error" className="rx-status error"><CircleAlert size={16}/>Enter a valid send amount to continue.</div>}</form></main>
    <footer><span>QUICKXCHANGE STANDARD</span><p>Every order starts with a readable route, a real network, and a clear expectation.</p><button data-testid="button-copy-standard" type="button" onClick={() => navigator.clipboard?.writeText('QuickXchange standard')}><Copy size={13}/> Copy reference</button></footer></div>;
}