export const publishedSiteContentStub = {
  pages: [],
  navigation: [],
  partnerLogos: [],
  socialTrust: {
    socialTitle: "Follow us",
    trustTitle: "Trusted exchange",
    instagramUrl: null,
    xUrl: null,
    facebookUrl: null,
    telegramUrl: null,
    items: [],
  },
  branding: {
    lightLogoPath: "/quick-change-logo.png",
    darkLogoPath: "/quick-change-logo.png",
    mobileLogoPath: null,
    faviconPath: null,
    logoWidth: 240,
    logoHeight: 64,
    logoMaxWidth: 240,
    desktopLogoWidth: 138,
    desktopLogoMaxHeight: 30,
    tabletLogoWidth: 130,
    tabletLogoMaxHeight: 28,
    mobileLogoWidth: 116,
    mobileLogoMaxHeight: 28,
    alignment: "left",
  },
};