export type TelegramLocale = "en" | "fr" | "ar" | "es" | "de" | "ru" | "uk" | "ko";
const supported = new Set<TelegramLocale>(["en", "fr", "ar", "es", "de", "ru", "uk", "ko"]);
export function localeOf(value?: string | null): TelegramLocale {
  const short = value?.toLowerCase().split("-")[0] as TelegramLocale | undefined;
  return short && supported.has(short) ? short : "en";
}
const copy: Record<TelegramLocale, Record<string, string>> = {
  en: { welcome: "Welcome to <b>QuickXchange</b>.", exchange: "Exchange", track: "Track Order", orders: "My Orders", support: "Support", website: "Website", language: "Language", choose: "Choose an option:", swap: "Swap", convert: "Convert", cancelled: "Cancelled.", tracking: "Send your order ID and tracking token separated by a space.", noOrders: "No Telegram-linked orders yet.", supportText: "Our support team is ready to help.", askAmount: "Enter the amount to exchange.", received: "Your request was received. Use Track Order for updates.", send: "Choose what you want to send:", receive: "Choose what you want to receive:", email: "Send your email address for order updates.", destination: "Send the destination wallet address.", review: "Review your QuickXchange order:", confirm: "Confirm", cancel: "Cancel", optionalRefund: "Optional refund address (or tap Skip):", skip: "Skip", invalid: "That value is not valid. Please try again.", unavailable: "QuickXchange exchange routes are temporarily unavailable.", order: "Order", status: "Status", amount: "Amount", quoteReceived: "Live quote received.", invalidEmail: "Please enter a valid email address.", expired: "This exchange session expired. Please start again.", processing: "Your order request is still being finalized. Please use My Orders shortly; do not resend the confirmation.", memo: "Send the memo or tag.", invalidAddress: "That address is not valid for the selected route. Please try again.", refundInvalid: "That refund address is not valid. Try again or tap Skip.", stepError: "QuickXchange could not complete that step. Please try again.", privateOnly: "Please open this bot in a private chat to continue.", reconciled: "was recovered safely.", notification: "is now", deposit: "Deposit address" },
  fr: { welcome: "Bienvenue sur <b>QuickXchange</b>.", exchange: "Échanger", track: "Suivre une commande", orders: "Mes commandes", support: "Assistance", website: "Site web", language: "Langue", choose: "Choisissez une option :", swap: "Swap", convert: "Convertir", cancelled: "Annulé.", tracking: "Envoyez l’ID et le jeton de suivi séparés par un espace.", noOrders: "Aucune commande Telegram liée.", supportText: "Notre équipe est prête à vous aider.", askAmount: "Saisissez le montant à échanger.", received: "Demande reçue. Utilisez Suivre une commande pour les mises à jour." },
  ar: { welcome: "مرحباً بك في <b>QuickXchange</b>.", exchange: "تبادل", track: "تتبع الطلب", orders: "طلباتي", support: "الدعم", website: "الموقع", language: "اللغة", choose: "اختر خياراً:", swap: "مبادلة", convert: "تحويل", cancelled: "تم الإلغاء.", tracking: "أرسل رقم الطلب ورمز التتبع مفصولين بمسافة.", noOrders: "لا توجد طلبات مرتبطة بتيليغرام.", supportText: "فريق الدعم جاهز لمساعدتك.", askAmount: "أدخل المبلغ المراد تبادله.", received: "تم استلام طلبك. استخدم تتبع الطلب للتحديثات." },
  es: { welcome: "Bienvenido a <b>QuickXchange</b>.", exchange: "Intercambiar", track: "Seguir pedido", orders: "Mis pedidos", support: "Soporte", website: "Sitio web", language: "Idioma", choose: "Elige una opción:", swap: "Swap", convert: "Convertir", cancelled: "Cancelado.", tracking: "Envía el ID y el token de seguimiento separados por un espacio.", noOrders: "Aún no hay pedidos vinculados.", supportText: "Nuestro equipo está listo para ayudarte.", askAmount: "Introduce el importe a intercambiar.", received: "Solicitud recibida. Usa Seguir pedido para ver actualizaciones." },
  de: { welcome: "Willkommen bei <b>QuickXchange</b>.", exchange: "Tauschen", track: "Bestellung verfolgen", orders: "Meine Bestellungen", support: "Support", website: "Website", language: "Sprache", choose: "Option auswählen:", swap: "Swap", convert: "Konvertieren", cancelled: "Abgebrochen.", tracking: "Sende Bestell-ID und Tracking-Token getrennt durch ein Leerzeichen.", noOrders: "Noch keine verknüpften Bestellungen.", supportText: "Unser Support hilft dir gerne.", askAmount: "Gib den Tauschbetrag ein.", received: "Anfrage erhalten. Nutze Bestellung verfolgen für Updates." },
  ru: { welcome: "Добро пожаловать в <b>QuickXchange</b>.", exchange: "Обмен", track: "Отследить заказ", orders: "Мои заказы", support: "Поддержка", website: "Сайт", language: "Язык", choose: "Выберите действие:", swap: "Обмен", convert: "Конвертация", cancelled: "Отменено.", tracking: "Отправьте ID заказа и токен через пробел.", noOrders: "Связанных заказов пока нет.", supportText: "Служба поддержки готова помочь.", askAmount: "Введите сумму обмена.", received: "Запрос принят. Используйте отслеживание заказа." },
  uk: { welcome: "Вітаємо в <b>QuickXchange</b>.", exchange: "Обмін", track: "Відстежити замовлення", orders: "Мої замовлення", support: "Підтримка", website: "Сайт", language: "Мова", choose: "Оберіть дію:", swap: "Обмін", convert: "Конвертація", cancelled: "Скасовано.", tracking: "Надішліть ID замовлення та токен через пробіл.", noOrders: "Пов’язаних замовлень ще немає.", supportText: "Служба підтримки готова допомогти.", askAmount: "Введіть суму обміну.", received: "Запит прийнято. Використовуйте відстеження замовлення." },
  ko: { welcome: "<b>QuickXchange</b>에 오신 것을 환영합니다.", exchange: "교환", track: "주문 추적", orders: "내 주문", support: "고객 지원", website: "웹사이트", language: "언어", choose: "옵션을 선택하세요:", swap: "스왑", convert: "변환", cancelled: "취소되었습니다.", tracking: "주문 ID와 추적 토큰을 공백으로 보내세요.", noOrders: "연결된 주문이 없습니다.", supportText: "지원팀이 도와드리겠습니다.", askAmount: "교환할 금액을 입력하세요.", received: "요청을 받았습니다. 주문 추적에서 업데이트를 확인하세요." },
};
const sharedKeys = ["send", "receive", "email", "destination", "review", "confirm", "cancel", "optionalRefund", "skip", "invalid", "unavailable", "order", "status", "amount", "quoteReceived", "invalidEmail", "expired", "processing", "memo", "invalidAddress", "refundInvalid", "stepError", "privateOnly", "reconciled", "notification", "deposit"];
for (const locale of supported) for (const key of sharedKeys) copy[locale][key] ??= copy.en[key];
Object.assign(copy.fr, { send: "Choisissez ce que vous envoyez :", receive: "Choisissez ce que vous recevez :", email: "Envoyez votre adresse e-mail.", destination: "Envoyez l’adresse du portefeuille de destination.", skip: "Ignorer", invalid: "Cette valeur est invalide. Réessayez." });
Object.assign(copy.ar, { send: "اختر ما تريد إرساله:", receive: "اختر ما تريد استلامه:", email: "أرسل بريدك الإلكتروني.", destination: "أرسل عنوان محفظة الوجهة.", skip: "تخطي", invalid: "هذه القيمة غير صالحة. حاول مرة أخرى." });
Object.assign(copy.es, { send: "Elige lo que envías:", receive: "Elige lo que recibes:", email: "Envía tu correo electrónico.", destination: "Envía la dirección de destino.", skip: "Omitir", invalid: "Este valor no es válido. Inténtalo de nuevo." });
Object.assign(copy.de, { send: "Wähle, was du sendest:", receive: "Wähle, was du erhältst:", email: "Sende deine E-Mail-Adresse.", destination: "Sende die Ziel-Wallet-Adresse.", skip: "Überspringen", invalid: "Dieser Wert ist ungültig. Bitte erneut versuchen." });
Object.assign(copy.ru, { send: "Выберите отправляемое:", receive: "Выберите получаемое:", email: "Отправьте адрес электронной почты.", destination: "Отправьте адрес кошелька получателя.", skip: "Пропустить", invalid: "Недопустимое значение. Попробуйте ещё раз." });
Object.assign(copy.uk, { send: "Оберіть валюту для відправлення:", receive: "Оберіть валюту для отримання:", email: "Надішліть електронну адресу.", destination: "Надішліть адресу гаманця отримувача.", skip: "Пропустити", invalid: "Неприпустиме значення. Спробуйте ще раз." });
Object.assign(copy.ko, { send: "보낼 자산을 선택하세요:", receive: "받을 자산을 선택하세요:", email: "이메일 주소를 보내세요.", destination: "받는 지갑 주소를 보내세요.", skip: "건너뛰기", invalid: "유효하지 않은 값입니다. 다시 시도하세요." });
Object.assign(copy.fr, { order: "Commande", status: "Statut", amount: "Montant", quoteReceived: "Cours en direct reçu.", invalidEmail: "Saisissez une adresse e-mail valide.", expired: "Cette session a expiré.", processing: "Votre demande est en cours de traitement." });
Object.assign(copy.es, { order: "Pedido", status: "Estado", amount: "Importe", quoteReceived: "Cotización recibida.", invalidEmail: "Introduce un correo válido.", expired: "La sesión ha caducado.", processing: "Tu solicitud se está procesando." });
Object.assign(copy.de, { order: "Bestellung", status: "Status", amount: "Betrag", quoteReceived: "Live-Kurs erhalten.", invalidEmail: "Gib eine gültige E-Mail ein.", expired: "Diese Sitzung ist abgelaufen.", processing: "Deine Anfrage wird verarbeitet." });
Object.assign(copy.ru, { order: "Заказ", status: "Статус", amount: "Сумма", quoteReceived: "Курс получен.", invalidEmail: "Введите корректный e-mail.", expired: "Сессия истекла.", processing: "Запрос обрабатывается." });
Object.assign(copy.uk, { order: "Замовлення", status: "Статус", amount: "Сума", quoteReceived: "Курс отримано.", invalidEmail: "Введіть коректний e-mail.", expired: "Сеанс завершено.", processing: "Запит обробляється." });
Object.assign(copy.ar, { order: "الطلب", status: "الحالة", amount: "المبلغ", quoteReceived: "تم استلام السعر.", invalidEmail: "أدخل بريداً صالحاً.", expired: "انتهت الجلسة.", processing: "جارٍ تنفيذ طلبك." });
Object.assign(copy.ko, { order: "주문", status: "상태", amount: "금액", quoteReceived: "실시간 견적을 받았습니다.", invalidEmail: "유효한 이메일을 입력하세요.", expired: "세션이 만료되었습니다.", processing: "요청을 처리하고 있습니다." });
for (const locale of supported) {
  copy[locale].optionalRefund ??= locale === "fr" ? "Adresse de remboursement facultative (ou Ignorer) :" : locale === "es" ? "Dirección de reembolso opcional (u Omitir):" : locale === "de" ? "Optionale Rückerstattungsadresse (oder Überspringen):" : locale === "ru" ? "Необязательный адрес возврата (или Пропустить):" : locale === "uk" ? "Необов’язкова адреса повернення (або Пропустити):" : locale === "ar" ? "عنوان استرداد اختياري (أو تخطي):" : locale === "ko" ? "선택적 환불 주소 (또는 건너뛰기):" : copy.en.optionalRefund;
}
Object.assign(copy.fr, { memo: "Envoyez le mémo ou le tag.", invalidAddress: "Cette adresse n’est pas valide pour cette route.", refundInvalid: "Cette adresse de remboursement est invalide.", stepError: "Impossible de terminer cette étape. Réessayez." });
Object.assign(copy.es, { memo: "Envía el memo o la etiqueta.", invalidAddress: "Esta dirección no es válida para esta ruta.", refundInvalid: "La dirección de reembolso no es válida.", stepError: "No se pudo completar este paso. Inténtalo de nuevo." });
Object.assign(copy.de, { memo: "Sende Memo oder Tag.", invalidAddress: "Diese Adresse ist für diese Route ungültig.", refundInvalid: "Diese Rückerstattungsadresse ist ungültig.", stepError: "Dieser Schritt konnte nicht abgeschlossen werden. Bitte erneut versuchen." });
Object.assign(copy.ru, { memo: "Отправьте memo или тег.", invalidAddress: "Этот адрес недействителен для выбранного маршрута.", refundInvalid: "Адрес возврата недействителен.", stepError: "Не удалось завершить этот шаг. Попробуйте ещё раз." });
Object.assign(copy.uk, { memo: "Надішліть memo або тег.", invalidAddress: "Ця адреса недійсна для цього маршруту.", refundInvalid: "Адреса повернення недійсна.", stepError: "Не вдалося завершити цей крок. Спробуйте ще раз." });
Object.assign(copy.ar, { memo: "أرسل المذكرة أو الوسم.", invalidAddress: "هذا العنوان غير صالح لهذا المسار.", refundInvalid: "عنوان الاسترداد غير صالح.", stepError: "تعذر إكمال هذه الخطوة. حاول مرة أخرى." });
Object.assign(copy.ko, { memo: "메모 또는 태그를 보내세요.", invalidAddress: "이 경로에 유효하지 않은 주소입니다.", refundInvalid: "환불 주소가 유효하지 않습니다.", stepError: "단계를 완료하지 못했습니다. 다시 시도하세요." });
export function t(locale: TelegramLocale, key: string) { return copy[locale][key] ?? copy.en[key] ?? key; }
export function languageButtons() {
  return [["en", "fr", "ar", "es"], ["de", "ru", "uk", "ko"]].map(row =>
    row.map(code => ({ text: code.toUpperCase(), callback_data: `lang:${code}` })));
}