import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, ChevronDown, Clipboard, Clock3, Copy, ExternalLink, Flag, MoreHorizontal, Send, ShieldCheck, UserRound } from 'lucide-react';

const stages = [
  { label: 'Funds received', time: '09:42', done: true },
  { label: 'Confirmations', time: '10:17', done: true },
  { label: 'Payout queue', time: 'now', done: false },
  { label: 'Released', time: '—', done: false },
];

export function DispatchBoard() {
  const [active, setActive] = useState<'work' | 'record'>('work');
  const [message, setMessage] = useState('Your Bitcoin deposit is confirmed. Your USDC payout is in the release queue.');
  const [sent, setSent] = useState(false);
  const [copied, setCopied] = useState(false);
  const [status, setStatus] = useState('Ready for release');

  const copyReference = () => {
    setCopied(true);
    window.setTimeout(() => setCopied(false), 1400);
  };

  return (
    <div className="dispatch-shell">
      <style>{`
        @import url('https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&family=Fraunces:opsz,wght@9..144,600;9..144,700&family=Manrope:wght@400;500;600;700;800&display=swap');
        .dispatch-shell { --ink:#20373a; --muted:#708182; --line:#d9dfd5; --cream:#f4f0e7; --paper:#fcfaf4; --mint:#d9e8d9; --olive:#52644f; --coral:#de694f; min-height:100%; background:var(--cream); color:var(--ink); font-family:Manrope,sans-serif; padding:22px; box-sizing:border-box; }
        .dispatch-shell *{box-sizing:border-box}.dispatch-shell button,.dispatch-shell select,.dispatch-shell textarea{font:inherit}.dispatch-shell button{cursor:pointer}
        .dispatch-app{max-width:1240px;margin:auto;overflow:hidden;background:var(--paper);border:1px solid #cbd3c8;box-shadow:0 22px 45px #63736624}
        .dispatch-top{height:74px;padding:0 27px;display:flex;align-items:center;justify-content:space-between;border-bottom:1px solid var(--line)}
        .dispatch-brand{font-family:Fraunces,serif;font-size:22px;letter-spacing:-1px}.dispatch-brand b{color:var(--coral);font-weight:700}.dispatch-brand i{display:inline-block;width:10px;height:10px;background:var(--coral);border-radius:50%;margin:0 6px 1px 0}
        .dispatch-breadcrumb{font-family:'DM Mono',monospace;color:#7b8982;font-size:11px;letter-spacing:.05em}.dispatch-breadcrumb strong{color:var(--ink);font-weight:500}
        .dispatch-user{display:flex;gap:10px;align-items:center;font-size:12px;font-weight:700}.dispatch-user span{display:grid;place-items:center;background:#e7ddd1;width:30px;height:30px;border-radius:50%;font-size:10px}
        .dispatch-body{display:grid;grid-template-columns:255px 1fr;min-height:692px}.dispatch-rail{background:#e8eee4;border-right:1px solid var(--line);padding:29px 20px;position:relative}.dispatch-order-kicker,.dispatch-label{font-family:'DM Mono',monospace;font-size:10px;letter-spacing:.12em;color:#6f8175}.dispatch-order-kicker{margin-bottom:10px}.dispatch-order-id{font-family:Fraunces,serif;font-size:25px;line-height:1.05;margin:0 0 6px}.dispatch-sub{font-family:'DM Mono',monospace;color:#718079;font-size:10px;overflow-wrap:anywhere;line-height:1.6}
        .dispatch-rail h3{font-size:11px;text-transform:uppercase;letter-spacing:.1em;margin:38px 0 18px;color:#556859}.dispatch-stage{position:relative;display:grid;grid-template-columns:24px 1fr auto;gap:9px;align-items:center;margin:0 0 24px;font-size:12px;font-weight:700}.dispatch-stage:before{content:"";position:absolute;left:10px;top:22px;width:1px;height:26px;background:#bfcabe}.dispatch-stage:last-of-type:before{display:none}.dispatch-stage-dot{width:21px;height:21px;border:1px solid #aebbaa;border-radius:50%;display:grid;place-items:center;background:#edf2e9;color:#53664d}.dispatch-stage.current .dispatch-stage-dot{background:var(--coral);border-color:var(--coral);color:#fff}.dispatch-stage time{font-family:'DM Mono',monospace;color:#84918a;font-size:10px}.dispatch-stage.current:after{content:"";width:7px;height:7px;border-radius:50%;background:var(--coral);position:absolute;left:-14px}.rail-alert{position:absolute;bottom:22px;left:20px;right:20px;border-top:1px solid #c4d0c2;padding-top:18px}.rail-alert p{font-size:11px;line-height:1.55;margin:5px 0 0;color:#64746b}.rail-alert strong{font-size:11px}
        .dispatch-main{padding:26px 30px 36px}.dispatch-main-header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:25px}.dispatch-main-header h1{font-family:Fraunces,serif;font-size:34px;letter-spacing:-1.5px;margin:6px 0 3px}.dispatch-main-header p{margin:0;color:var(--muted);font-size:12px}.back-link{border:0;background:transparent;color:#506153;font-size:11px;font-weight:800;display:flex;gap:7px;align-items:center;padding:7px 0}.tabs{display:flex;gap:22px;border-bottom:1px solid var(--line);margin-bottom:26px}.tabs button{border:0;background:none;padding:0 0 12px;color:#7e8b84;font-size:12px;font-weight:800;border-bottom:2px solid transparent}.tabs button.active{color:var(--ink);border-color:var(--coral)}
        .dispatch-work{display:grid;grid-template-columns:minmax(0,1fr) 246px;gap:22px}.workspace{border:1px solid var(--line);background:#fffdf8}.workspace-top{padding:19px 21px 16px;border-bottom:1px solid var(--line);display:flex;align-items:center;justify-content:space-between}.workspace-top h2{font-family:Fraunces,serif;font-size:20px;margin:4px 0 0}.status-select{appearance:none;background:#f4ead7 url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='12' height='12' fill='none' stroke='%233a5045' stroke-width='1.5'%3E%3Cpath d='m3 4.5 3 3 3-3'/%3E%3C/svg%3E") no-repeat right 9px center;border:0;padding:7px 29px 7px 10px;color:#405743;font-weight:800;font-size:11px;border-radius:2px}.instruction{padding:18px 21px;background:#f8f5ed;border-bottom:1px solid var(--line);display:flex;gap:11px;align-items:flex-start}.instruction-icon{color:var(--coral);margin-top:2px}.instruction p{font-size:12px;line-height:1.55;margin:0;color:#4c5f58}.instruction strong{display:block;color:var(--ink);margin-bottom:2px}.route{display:grid;grid-template-columns:1fr 34px 1fr;padding:20px 21px;align-items:center}.currency-box{padding:14px 0;border-bottom:2px solid var(--ink)}.currency-box.out{border-bottom-color:#9bb39d}.currency-name{display:flex;justify-content:space-between;align-items:center;font-size:12px;font-weight:800}.currency-name strong{font-family:Fraunces,serif;font-size:23px;letter-spacing:-.5px}.currency-box p{font-family:'DM Mono',monospace;font-size:11px;margin:9px 0 0;color:#63736b}.route-arrow{display:grid;place-items:center;color:var(--coral)}.release-fields{padding:0 21px 20px;display:grid;grid-template-columns:1fr 1fr;gap:15px}.release-field label{display:block;margin-bottom:7px;font-size:10px;color:#71817a;font-family:'DM Mono',monospace;letter-spacing:.05em}.release-field div{border:1px solid var(--line);padding:10px;font-family:'DM Mono',monospace;font-size:11px;color:#375049;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.release-field button{border:0;background:transparent;color:var(--olive);padding:0 0 0 5px;vertical-align:middle}.release-footer{background:#244242;padding:16px 21px;display:flex;justify-content:space-between;align-items:center;color:#e7efe2}.release-footer p{margin:0;font-size:11px;line-height:1.5}.release-footer strong{display:block;font-size:12px}.release-button{border:0;background:var(--coral);color:#fffaf1;padding:11px 14px;display:flex;align-items:center;gap:7px;font-size:11px;font-weight:800}.release-button:disabled{background:#86938a}
        .side-stack{display:grid;gap:14px;align-content:start}.mini-card{border:1px solid var(--line);background:#fffdf8;padding:16px}.mini-card h3{font-family:Fraunces,serif;font-size:17px;margin:4px 0 12px}.contact-row{display:flex;gap:10px;align-items:center;border-bottom:1px solid #e4e7de;padding-bottom:12px}.contact-avatar{width:31px;height:31px;border-radius:50%;background:#d9e8d9;display:grid;place-items:center;font-family:Fraunces,serif;font-weight:700}.contact-row strong{font-size:11px;display:block}.contact-row span{font-size:10px;color:#77867f}.message-box{width:100%;resize:none;min-height:92px;background:#f7f4ec;border:1px solid #e1e2d9;padding:9px;font-size:11px;line-height:1.5;color:#51635a;outline-color:#9bad9b}.message-send{margin-top:8px;width:100%;border:1px solid #5a715c;background:#eff4eb;color:#3c563e;padding:8px;font-size:10px;font-weight:800;display:flex;justify-content:center;gap:6px}.note-item{padding:10px 0;border-top:1px solid #e4e7de}.note-item:first-of-type{border-top:0}.note-item p{margin:2px 0;font-size:10px;line-height:1.5;color:#607169}.note-item span{font-family:'DM Mono',monospace;font-size:9px;color:#88948e}
        .record{border:1px solid var(--line);background:#fffdf8;padding:20px}.record-row{display:grid;grid-template-columns:145px 1fr;gap:20px;border-bottom:1px solid var(--line);padding:14px 0;font-size:12px}.record-row:last-child{border:0}.record-row span{color:#74837b;font-family:'DM Mono',monospace;font-size:10px}.record-row strong{font-weight:700}.record-row small{display:block;color:#6d7c74;margin-top:5px;font-family:'DM Mono',monospace;overflow-wrap:anywhere}
        @media(max-width:760px){.dispatch-shell{padding:0}.dispatch-app{border:0}.dispatch-body{grid-template-columns:1fr}.dispatch-rail{display:none}.dispatch-main{padding:19px 16px}.dispatch-top{padding:0 16px}.dispatch-breadcrumb{display:none}.dispatch-main-header h1{font-size:29px}.dispatch-work{grid-template-columns:1fr}.route{grid-template-columns:1fr 25px 1fr;padding:16px}.release-fields{grid-template-columns:1fr}.workspace-top{align-items:flex-start;gap:10px}.release-footer{align-items:flex-start;gap:10px}.dispatch-user div{display:none}}
      `}</style>
      <div className="dispatch-app">
        <header className="dispatch-top">
          <div className="dispatch-brand"><i />rowan<b>desk</b></div>
          <div className="dispatch-breadcrumb">LIVE OPERATIONS / <strong>SETTLEMENT DESK</strong></div>
          <div className="dispatch-user"><span>MC</span><div>Maya Chen<br /><small>Settlement lead</small></div><MoreHorizontal size={17} /></div>
        </header>
        <div className="dispatch-body">
          <aside className="dispatch-rail">
            <div className="dispatch-order-kicker">ACTIVE SETTLEMENT</div><h2 className="dispatch-order-id">#7E4A19C2</h2><div className="dispatch-sub">ord_01JH6TQ8Y7E4A19C2B5MVPK3ND</div>
            <h3>Release path</h3>
            {stages.map((stage, index) => <div className={`dispatch-stage ${index === 2 ? 'current' : ''}`} key={stage.label}><span className="dispatch-stage-dot">{stage.done ? <Check size={12} /> : index + 1}</span><span>{stage.label}</span><time>{stage.time}</time></div>)}
            <div className="rail-alert"><div className="dispatch-label">DESK NOTE</div><strong>Low-risk, priority client</strong><p>Source of funds was reviewed. Hold release until the outgoing hash is attached.</p></div>
          </aside>
          <main className="dispatch-main">
            <div className="dispatch-main-header"><div><div className="dispatch-label">MANUAL SETTLEMENT</div><h1>Release USDC payout</h1><p>Daniel Ortiz · opened Jan 22, 2025 at 09:42 UTC</p></div><button className="back-link"><ArrowLeft size={14} /> ALL ORDERS</button></div>
            <div className="tabs"><button className={active === 'work' ? 'active' : ''} onClick={() => setActive('work')}>Release workspace</button><button className={active === 'record' ? 'active' : ''} onClick={() => setActive('record')}>Order record</button></div>
            {active === 'work' ? <div className="dispatch-work">
              <section className="workspace">
                <div className="workspace-top"><div><div className="dispatch-label">NEXT ACTION</div><h2>Prepare external transfer</h2></div><select className="status-select" value={status} onChange={(event) => setStatus(event.target.value)}><option>Ready for release</option><option>Awaiting review</option><option>Released</option></select></div>
                <div className="instruction"><ShieldCheck className="instruction-icon" size={18} /><p><strong>Deposit requirements are met</strong>0.9825 BTC has three confirmations. Create the USDC transfer, attach its reference, then release this order.</p></div>
                <div className="route"><div className="currency-box"><div className="currency-name"><strong>0.9825 BTC</strong><span>Bitcoin</span></div><p>Deposit confirmed · 3 / 3 blocks</p></div><ArrowRight className="route-arrow" size={18} /><div className="currency-box out"><div className="currency-name"><strong>41,278.46 USDC</strong><span>Polygon</span></div><p>Quoted at 42,122.92 USDC / BTC</p></div></div>
                <div className="release-fields"><div className="release-field"><label>POLYGON DESTINATION</label><div>0x71C4e8A33d29aBA7C9e26B4Bf89b7F2c6eB841D3 <button onClick={copyReference} title="Copy address">{copied ? <Check size={13} /> : <Copy size={13} />}</button></div></div><div className="release-field"><label>OUTGOING REFERENCE</label><div>Awaiting transfer hash</div></div></div>
                <div className="release-footer"><p><strong>{status === 'Released' ? 'Payout released to the network' : 'One release action remains'}</strong>{status === 'Released' ? 'The customer will see the transaction reference shortly.' : 'You can revoke this action only before it reaches the provider.'}</p><button className="release-button" disabled={status === 'Released'} onClick={() => setStatus('Released')}><Flag size={14} /> {status === 'Released' ? 'Released' : 'Release payout'}</button></div>
              </section>
              <aside className="side-stack">
                <section className="mini-card"><div className="dispatch-label">CUSTOMER LINE</div><h3>Daniel Ortiz</h3><div className="contact-row"><div className="contact-avatar">DO</div><div><strong>daniel.ortiz@example.com</strong><span>Verified customer · 12 prior orders</span></div><ExternalLink size={13} color="#6d8074" /></div><textarea aria-label="Customer update" className="message-box" value={message} onChange={e => setMessage(e.target.value)} /><button className="message-send" onClick={() => setSent(true)}><Send size={12} /> {sent ? 'Update queued' : 'Send customer update'}</button></section>
                <section className="mini-card"><div className="dispatch-label">RECENT HANDOFFS</div><h3>Desk activity</h3><div className="note-item"><span>10:18 · MAYA CHEN</span><p>Moved order into payout queue.</p></div><div className="note-item"><span>10:17 · SYSTEM</span><p>Third Bitcoin confirmation received.</p></div><div className="note-item"><span>09:46 · OPS DESK</span><p>Assigned to Maya Chen.</p></div></section>
              </aside>
            </div> : <section className="record"><div className="record-row"><span>ORDER</span><strong>BTC → USDC <small>ord_01JH6TQ8Y7E4A19C2B5MVPK3ND</small></strong></div><div className="record-row"><span>CUSTOMER</span><strong>Daniel Ortiz <small>daniel.ortiz@example.com</small></strong></div><div className="record-row"><span>INCOMING TX</span><strong>8f2c1d9a004c93d62f71d5a1826de80bfc3a91a7 <small>Bitcoin · 3 confirmations</small></strong></div><div className="record-row"><span>DESTINATION</span><strong>0x71C4e8A33d29aBA7C9e26B4Bf89b7F2c6eB841D3 <small>Polygon · USDC</small></strong></div><div className="record-row"><span>ASSIGNED</span><strong><UserRound size={13} /> Maya Chen <small>Settlement lead</small></strong></div><div className="record-row"><span>CREATED</span><strong><Clock3 size={13} /> Jan 22, 2025, 09:42:16 UTC</strong></div></section>}
          </main>
        </div>
      </div>
    </div>
  );
}