import { useState } from 'react';
import { Archive, ArrowLeft, ArrowRight, Check, Save, UserRound } from 'lucide-react';
import './_group.css';
import './Redesigned.css';

const history = [
  ['Settlement status updated', 'maya.chen@novaswap.io', 'funds_confirmed → payout_processing', 'Jan 22, 2025, 10:18:42 AM'],
  ['Order updated', 'maya.chen@novaswap.io', 'Incoming reference: 8f2c1d…91a7', 'Jan 22, 2025, 10:17:09 AM'],
  ['Assignment updated', 'ops@novaswap.io', 'Assignee: maya.chen@novaswap.io', 'Jan 22, 2025, 9:46:31 AM'],
  ['Order created', 'Customer', 'Manual settlement order opened', 'Jan 22, 2025, 9:42:16 AM'],
];

function Details({ receive = false }: { receive?: boolean }) {
  const rows = receive ? [['Amount', '41,278.46 USDC', true], ['Network / payment method', 'Polygon'], ['Destination address', '0x71C4e8A33d29aBA7C9e26B4Bf89b7F2c6eB841D3'], ['Settlement speed', 'Same business day'], ['Quote rate', '1 BTC = 42,122.92 USDC']] : [['Amount', '0.9825 BTC', true], ['Network / payment method', 'Bitcoin'], ['Deposit address', 'bc1q9v7z4jzfh0ml7c2krk3wq0wpcckzh4f8u62eqa'], ['Refund address', 'bc1qp0az8xg6le8xewyut9xyywqp8j6vkgzx44j8cq'], ['Required confirmations', '3 network confirmations']];
  return <section className="ro-card"><header className="ro-card-head"><div><span className="ro-number">{receive ? '02 / PAYOUT' : '01 / FUNDING'}</span><h2>{receive ? 'Customer receives' : 'Customer sends'}</h2></div></header><dl className="ro-details">{rows.map(([label, value, key]) => <div className={key ? 'key' : ''} key={label as string}><dt>{label}</dt><dd>{value}</dd></div>)}</dl></section>;
}

export function Redesigned() {
  const [status, setStatus] = useState('payout_processing'); const [assignee, setAssignee] = useState('maya');
  const [incoming, setIncoming] = useState('8f2c1d9a004c93d62f71d5a1826de80bfc3a91a7'); const [outgoing, setOutgoing] = useState('');
  const [customerNote, setCustomerNote] = useState('Your Bitcoin deposit has been confirmed. We are preparing your USDC payout.');
  const [note, setNote] = useState('Source of funds reviewed. Priority client; complete payout before 14:00 UTC.'); const [saved, setSaved] = useState(false);
  const save = () => { setSaved(true); window.setTimeout(() => setSaved(false), 2200); };
  return <div className="order-details-redesigned"><div className="ro-shell">
    <header className="ro-topbar"><div className="ro-mark"><span />Nova<b>Swap</b></div><div className="ro-top-actions"><button className="ro-back" onClick={() => window.history.back()}><ArrowLeft size={14} /> Back to orders</button><span className="ro-avatar">MC</span></div></header>
    <div className="ro-crumb">OPERATIONS / MANUAL SWAPS / ORDER DETAILS</div><div className="ro-titleline"><div><h1>Order 7E4A19C2</h1><p className="ro-subid">ord_01JH6TQ8Y7E4A19C2B5MVPK3ND</p></div><span className="ro-status"><i /> Payout processing</span></div>
    <section className="ro-route"><div className="ro-route-head"><span className="ro-eyebrow">MANUAL SWAP · SETTLEMENT DESK</span><p>Created Jan 22, 2025, 9:42:16 AM</p></div><div className="ro-amounts"><div className="ro-leg"><small>CUSTOMER SENDS</small><strong>0.9825 BTC</strong></div><ArrowRight className="ro-arrow" size={22}/><div className="ro-leg"><small>CUSTOMER RECEIVES</small><strong>41,278.46 USDC</strong></div></div><div className="ro-steps">{['Awaiting funds','Funds confirmed','Payout processing','Payout sent','Completed'].map((x,i)=><div className={`ro-step ${i<2?'done':i===2?'now':''}`} key={x}><span>{i<2?<Check size={10}/>:i+1}</span>{x}</div>)}</div></section>
    <div className="ro-grid"><div className="ro-maincol"><Details/><Details receive/><section className="ro-card ro-control"><span className="ro-number">SETTLEMENT CONTROLS</span><h2>Prepare the next safe movement</h2><div className="ro-fields"><div className="ro-field"><label>Settlement status</label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="payout_processing">Payout processing</option><option value="payout_sent">Payout sent</option><option value="completed">Completed</option></select><p className="ro-hint">Later statuses are recorded on save.</p></div><div className="ro-field"><label>Assigned operator</label><select value={assignee} onChange={e=>setAssignee(e.target.value)}><option value="">Unassigned</option><option value="maya">maya.chen@novaswap.io · owner</option><option value="jon">jon.bell@novaswap.io · operator</option></select></div><div className="ro-field full"><label>Incoming transaction reference</label><input value={incoming} onChange={e=>setIncoming(e.target.value)}/></div><div className="ro-field full"><label>Outgoing transaction reference</label><input value={outgoing} placeholder="Add payout transaction hash" onChange={e=>setOutgoing(e.target.value)}/></div><div className="ro-field"><label>Customer-safe note</label><textarea rows={3} value={customerNote} onChange={e=>setCustomerNote(e.target.value)}/></div><div className="ro-field"><label>Internal note</label><textarea rows={3} value={note} onChange={e=>setNote(e.target.value)}/></div></div><div className="ro-action-row"><button className="ro-button ro-save" onClick={save}><Save size={14}/> Save changes</button><button className="ro-button ro-assign" onClick={save}><UserRound size={14}/> Update assignment</button>{saved&&<span className="ro-flash">Changes saved</span>}<button className="ro-button ro-archive" onClick={() => window.confirm('Archive order 7E4A19C2?')}><Archive size={14}/> Archive order</button></div></section></div>
    <aside className="ro-side"><section className="ro-card ro-people"><span className="ro-number">ORDER CONTEXT</span><h3>People & ownership</h3><div className="ro-person"><small>Customer</small><strong>Daniel Ortiz</strong><span>daniel.ortiz@example.com</span></div><div className="ro-person"><small>Assigned operator</small><strong>maya.chen@novaswap.io</strong><span>Order owner</span></div></section><section className="ro-card ro-note"><span className="ro-number">OPERATOR GUIDANCE</span><h3>Verify payout destination</h3><p>Confirm the Polygon destination and attach the outgoing transaction reference before advancing to Payout sent.</p></section><section className="ro-card ro-history"><span className="ro-number">IMMUTABLE HISTORY · {history.length}</span><h2>Order activity</h2>{history.map(([title,actor,detail,time])=><div className="ro-event" key={time}><strong>{title}</strong><span>{actor}<br/>{detail}</span><time>{time}</time></div>)}</section></aside></div>
  </div></div>;
}